"""empty message

Revision ID: 53e08233845d
Revises: 0a26581201f6
Create Date: 2019-02-19 07:52:54.596873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53e08233845d'
down_revision = '0a26581201f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('service', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'service')
    # ### end Alembic commands ###
