"""empty message

Revision ID: bace42ba60d5
Revises: c61aa467b98d
Create Date: 2019-03-24 07:14:21.626427

"""
from alembic import op
import sqlalchemy as sa

from dataaccess.models import Role


# revision identifiers, used by Alembic.
revision = 'bace42ba60d5'
down_revision = 'c61aa467b98d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sql', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
    roles_table = Role.__table__
    op.bulk_insert(roles_table, [
        {'name': 'query-builder', 'description': 'This role allows adding new queries', 'internal': True},
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queries')
    # ### end Alembic commands ###
