"""empty message

Revision ID: c61aa467b98d
Revises: 53e08233845d
Create Date: 2019-02-21 06:43:40.566099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61aa467b98d'
down_revision = '53e08233845d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('created_on_idx', 'audit_entries', ['created_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('created_on_idx', table_name='audit_entries')
    # ### end Alembic commands ###
