"""empty message

Revision ID: c89c89eca14e
Revises: 9ebf5534c878
Create Date: 2019-05-07 12:44:33.750495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89c89eca14e'
down_revision = '9ebf5534c878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'datasets', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'datasets', type_='unique')
    # ### end Alembic commands ###
