"""empty message

Revision ID: d406714ea12f
Revises: c89c89eca14e
Create Date: 2019-05-19 08:36:14.910619

"""
from alembic import op
import sqlalchemy as sa

from dataaccess.models import Role


# revision identifiers, used by Alembic.
revision = 'd406714ea12f'
down_revision = 'c89c89eca14e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_config', sa.Column('reports_location', sa.String(), nullable=True))
    # ### end Alembic commands ###
    roles_table = Role.__table__
    op.bulk_insert(roles_table, [
        {'name': 'report-viewer', 'description': 'This role allows viewing static reports', 'internal': True},
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_config', 'reports_location')
    # ### end Alembic commands ###
