"""empty message

Revision ID: 9ebf5534c878
Revises: bace42ba60d5
Create Date: 2019-03-25 08:29:24.502305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ebf5534c878'
down_revision = 'bace42ba60d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_config', sa.Column('driver_memory_mb', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_config', 'driver_memory_mb')
    # ### end Alembic commands ###
