"""empty message

Revision ID: d84edfa5f697
Revises: fb5a8d632e8b
Create Date: 2020-12-24 19:00:32.062185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd84edfa5f697'
down_revision = 'fb5a8d632e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
